### ISSUE TITLE
python 3?

### ISSUE THREAD

**Issue by fccoelho** [jmcclell/django-bootstrap-pagination#21]
Does it support python 3? pip install under python 3.3 failed.

**Comment by jplehmann** [comment]
Where does this stand? 

Or who has the most official and py3k compatible fork?

**Comment by jmcclell** [comment]
@jplehmann I'm not sure whose fork would be most compatible. I just don't use Python enough these days and haven't taken the time to commit to an official Python 3 version. I may do so in the future, but it just hasn't happened yet. One of the biggest issues with this project is a lack of tests so it's hard to make major changes like this if I want to maintain backwards compatibility, which is a goal of mine for now, at least. I would be thrilled for another developer to solve either of those issues, but I don't have the time nor the Python 3 expertise at this time to do so.

**Comment by kvdveer** [comment]
I've been using 1.5.1 from pypy on python 3.4 and 3.5.
I have yet to encounter any issues.
