### ISSUE TITLE
Modifying for other frameworks

### ISSUE THREAD

**Issue by jrhoads** [jmcclell/django-bootstrap-pagination#23]
Great package.  It did 99% of what I needed right out of the gate.
I happen to use foundation and most of the structure works.

I needed to change the "active" link class to "current"
I just copied the template (including directory) into my project and modified it there.
Template loading order took care of the rest.

Again, great work.

**Comment by jmcclell** [comment]
I don't have a particular desire to make this work for more than one framework. The chances of the disparity becoming too great between frameworks is too high. It makes more sense to maintain separate projects per framework, and to that end, you are more than welcome to fork this and make django-foundation-pagination :)
