### ISSUE TITLE
i18n and l10n

### ISSUE THREAD

**Issue by qcaron** [jmcclell/django-bootstrap-pagination#29]
Hi guys!

What about translating strings such as "Last Page" ? I can setup translation for the app and add French translation. Let me know if you are interested and/or have best practices about this.

Cheers!
Quentin

**Comment by staticdev** [comment]
It's would be a good feature. If you make a pull request, I will merge into my forked pagination.

**Comment by manikos** [comment]
What about Greek translations? I am willing to translate these strings.
How do I get started? I have never contributed to a package before. But I want to!

**Comment by hebertjulio** [comment]
I can translate to Portuguese. :)

**Comment by jmcclell** [comment]
Russian translation merged into next release. Other languages welcome via PR.
