### ISSUE TITLE
Parser?

### ISSUE THREAD

**Issue by Boogymanx** [jmcclell/django-bootstrap-pagination#36]
Hey, I'm trying to use your bootstrap_paginate template tag in a view (I know this isn't proper coding, but I need to write some dirty code as I'm getting close to the deadline and still have a lot of work). I saw that your bootstrap_paginate() requires two args: a parser and a token. I'm fairly certain the token is the page_obj, but I'm not sure what to use for parser and I couldn't immediately find what value I should put there. Could you point me in the right direction? 

Many thanks in advance, 
Boogy :)

**Comment by jmcclell** [comment]
For future reference, StackOverflow or something similar would likely garner a quicker response. For Django, custom template tags are passed a Parser object created by the framework itself.

https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/

You can probably poke around the Django source to get more information.
