### ISSUE TITLE
Lack of "centered" for "bootstrap_paginate"

### ISSUE THREAD

**Issue by ad-m** [jmcclell/django-bootstrap-pagination#38]
"bootstrap_pager" offer "centered' kwargs. I believe "bootstrap_paginate" should offer it too.

**Comment by jmcclell** [comment]
The underlying bootstrap pagination component does not have any options for alignment. You can either wrap your pagination object in a div to center it or extend the template and override the extra_classes block with a comma delimted list of class names to add. That's not very ideal, I agree. Extra classes or extra style overrides could be added as additional parameters, perhaps. Would welcome a PR for it for both pager or pagination.
