### ISSUE TITLE
Ampersands in URLs are not escaped

### ISSUE THREAD

**Issue by wetneb** [jmcclell/django-bootstrap-pagination#41]
The app does not escape ampersands in URLs, which produces the following invalid HTML:
<pre>
&lt;a title="Page 2 of 2" href="/foo?key=val&amp;page=2"&gt;2&lt;/a&gt;
</pre>
It should be:
<pre>
&lt;a title="Page 2 of 2" href="/foo?key=val&amp;amp;page=2"&gt;2&lt;/a&gt;
</pre>

**Comment by jmcclell** [comment]
Has this actually caused an issue for you? I don't claim to be a front end specialist and certainly would not disagree with the idea that we should adhere to standards as best as possible, but I've never once seen an actual issue with directly using an ampersand in an href. So, my question is more about curiosity than validity.

**Comment by wetneb** [comment]
Well, this only breaks my tests which check the validity of my HTML output. But you are right, it is otherwise very benign.

**Comment by jmcclell** [comment]
Give me a PR and I'll happily merge it in. Totally simple change and entirely valid, regardless of how benign it may otherwise be. :)

**Comment by wetneb** [comment]
Here it is: #45.
