### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by ad-m** [jmcclell/django-bootstrap-pagination#44]
Hello,

I  got warnings:
```
bootstrap_pagination/templatetags/bootstrap_pagination.py:213: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
```

Greetings,

**Comment by jmcclell** [comment]
Looks like I'll need to cut a non-BC version to deal with that. Looks like it is deprecated but not yet removed?

**Comment by ad-m** [comment]
It's only deprecation warning. It will removed in future release (1.10). Django 1.10 wasn't released yet.

" non-BC version" What do you mean?

**Comment by jmcclell** [comment]
Non-backwards compatible. If render is removed, I assume it's being replaced with something that won't be present in all older versions.

**Comment by kvdveer** [comment]
render() is not removed, it just takes slightly different parameters.
I'll submit a merge request later today.
