### ISSUE TITLE
show_index_range option adds additional queries by evaluating page.paginator.objectlist

### ISSUE THREAD

**Issue by bboogaard** [jmcclell/django-bootstrap-pagination#51]
Since updating to v. 1.6.0 I get additional queries when passing a page object to bootstrap_paginate. This is caused by evaluating the object_list attribute of the paginator of that page object (line 200 in templatetags/bootstrap_pagination.py). Could you change it so that it only is evaluated when you have the show_index_range option (passed in)?

**Comment by kvdveer** [comment]
Version 1.6.1 fixes the issue in the way you proposed.

Could you elaborate a bit on why this is an issue in the first place? I'd suspect the object list from which the paginator was constructed would be evaluated anyway elsewhere in the same page?
