### ISSUE TITLE
Bootstrap4 branch, active element still needs "page-item" class

### ISSUE THREAD

**Issue by danaki** [jmcclell/django-bootstrap-pagination#52]
According to template bs4.html an element either .active or .page-item, but it must be .page-item and one of them could also be .active.

Btw, do you really need settings.BOOTSTRAP_VERSION variable/check in the branch called "bs4"?

**Comment by kvdveer** [comment]
> According to template bs4.html an element either .active or .page-item, but it must be .page-item and one of them could also be .active.

Ah, thank you. I never had the time to actually check this. I'll apply this later today.

> Btw, do you really need settings.BOOTSTRAP_VERSION variable/check in the branch called "bs4"?

The BS4 branch (re-)introduces compatibility with bs2, adds bs4, and maintains compatibility with bs3. To do so, we need to signify which version of bootstrap you're using. As BS4 is still in alpha, it won't be the default for now, though that may change once BS4 is ready for prime time.
