### ISSUE TITLE
'QuerySet' object has no attribute 'paginator'

### ISSUE THREAD

**Issue by azmainamin** [jmcclell/django-bootstrap-pagination#54]
I get this error on: {% bootstrap_paginate deals %}, where deals is a query_set object. Maybe I am using it wrong, but if I don't put a query set object, what do I put there?

**Comment by kvdveer** [comment]
`bootstrap_paginate` only handles visuals of the pagination - not the actual pagination itself. For that you'll need django's [pagination](https://docs.djangoproject.com/en/1.9/topics/pagination/) object, typically constructed in the view.

**Comment by azmainamin** [comment]
Gotcha! Thanks a bunch!
