### ISSUE TITLE
current_app is removed from RequestContext in Django 1.10

### ISSUE THREAD

**Issue by beaugunderson** [jmcclell/django-bootstrap-pagination#56]
so there's a failure [here](https://github.com/jmcclell/django-bootstrap-pagination/blob/bc6d4f060b36418d7dc57ee4068e705b9bd28678/bootstrap_pagination/templatetags/bootstrap_pagination.py#L102) for example

as a sidenote; [Jazzband](https://jazzband.co/) is a collaborative maintainership organization if you're lacking time for this module! lots of Django modules there already :)

**Comment by rafalmp** [comment]
#53 supposedly fixes that

**Comment by camilonova** [comment]
Please merge the pull request and issue a new release

**Comment by beaugunderson** [comment]
Verifying that #53 fixes the issue I had. ✨

**Comment by jmcclell** [comment]
#53 merged to fix this, released as v1.6.2

**Comment by camilonova** [comment]
Thank you
