### ISSUE TITLE
Unicode strings support

### ISSUE THREAD

**Issue by manenko** [jmcclell/django-bootstrap-pagination#6]
Hello,

I tried to use i18n and non-ASCII symbols for _previous_label_, _next_label_, etc. and got UnicodeEncodeError:

> 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
> Exception Location: /**skipped**/bootstrap-pagination/templatetags/bootstrap_pagination.py in render, line 137

The problem is in code like this:
    previous_label = str(kwargs.get("previous_label", "&larr;"))

I replace _str_ with _unicode_ and everything works fine.

**Comment by MarkDoggen** [comment]
Could you push this fix to support unicode strings?
