### ISSUE TITLE
django.core.urlresolvers deprecated in Django 2.0

### ISSUE THREAD

**Issue by narrowfail** [jmcclell/django-bootstrap-pagination#64]
```
Invalid template library specified. 

ImportError raised when trying to load 'bootstrap_pagination.templatetags.bootstrap_pagination':
No module named 'django.core.urlresolvers'
```

> Deprecated since version 1.10:
> In older versions, these functions are located in django.core.urlresolvers. Importing from the old location will continue to work until Django 2.0.

**Comment by adilkhash** [comment]
Here is PR https://github.com/jmcclell/django-bootstrap-pagination/pull/66

**Comment by kvdveer** [comment]
I have merged your PR. Thanks for contributing.
