### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by Dulcin** [jmcclell/django-bootstrap-pagination#70]
Hi, I noticed the readme says:

> Note: This version is compatible with Bootstrap 3.x only! Please use the 1.0.x branch for Bootstrap 2 support.

Does it mean it does not support Bootstrap 4? I noticed the BS4 branch, but it gives a TemplateDoesNotExist error, see my reply in #50 

This is the only project I could find that is being actively maintained, but it needs some updating. I noticed no new activity in the BS4 branch for 2 years, are you planning on supporting BS4?

**Comment by joe513** [comment]
@Dulcin 
Hey, you can use this [one ](https://github.com/joe513/django-cool-pagination), but currently it works for python 3.x branch only.

**Comment by jmcclell** [comment]
Bootstrap 4 support for the Pagination tag is in the upcoming release. Pager is not supported past Bootstrap 3 currently as there is no equivalent construct in Bootstrap 4.
