### ISSUE TITLE
Incompatible with Django 2.1

### ISSUE THREAD

**Issue by ScottEvansDBCA** [jmcclell/django-bootstrap-pagination#71]
Just upgrading a project to Django 2.1 and found an error.
2.1 removes urls inline flags in the encode:
[url()’s support for inline flags in regular expression groups ((?i), (?L), (?m), (?s), and (?u)) is removed.](https://docs.djangoproject.com/en/2.1/releases/2.1/)

bootstrap_pagination.py line 85 url += '?' + url_get_params.urlencode() calls to django/http/request.py and gives an error: "'int' object has no attribute encode".
Have commented this out and the page loads but obviously pagination no longer works.

**Comment by timrichardson** [comment]
fixed in this fork: https://github.com/myasui/django-bootstrap-pagination

**Comment by jmcclell** [comment]
I've cherry-picked. Will be in the next release.
